name: test
on:
  push:
  pull_request:

jobs:
  test-deno:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["v2.x"]
    name: Test Deno on Version ${{ matrix.deno }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run tests in Deno
        run: deno test -A
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["v2.x"]
        node: ["26", "25", "24"]
    name: Test Node on Version ${{ matrix.node }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          deno-version: "latest"
    
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds

      - uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Build and test node
        run: deno task npm 0.0.0
